---
  - name: add user by array mode
    hosts: webserver1
    vars_files: vars/arrayuser.yml
    tasks:
      - name: add username "{{users['melody']['firstname']}}"
        user:
          user: "{{users['melody']['firstname']}}"
          password: "{{users['melody']['password']}}"
        register: output
      - name: show register output
        debug: var=output
