---
  - name: list my managed hosts facts
    hosts: website
    tasks:
      - name: list managed hosts facts
        debug:
          msg: |
            The IPv4 IP address is {{ansible_facts['default_ipv4']['address']}}
            The host name os {{ansible_facts['fqdn']}}
            The kernel version is {{ansible_facts['kernel']}}
            The network card is {{ansible_facts['interfaces']}}
