---
  - name: install lustre server
    hosts: client
    vars_files: vars/dkms_pkg.yml
    tasks:
      - name: create lustre.repo
        copy:
          src: /etc/yum.repos.d/lustre.repo
          dest: /etc/yum.repos.d/lustre.repo

      - name: yum install epel-release
        yum:
          name: epel-release
          state: latest

      - name: yum dkms_pkg
        yum :
          name: "{{pkg}}"
          state: latest

      - name: enable powertool
        command: 'dnf --enablerepo=powertools install device-mapper-devel libyaml-devel -y'

      - name: yum install dkms
        yum:
          name: dkms
          state: latest

      - name: yum install e2fsprogs
        yum:
          name: e2fsprogs
          state: latest
