---
  - name: install lustre server
    hosts:
      - client
    tasks:
      - name: yum lustre
        yum:
          name: 
            - lustre-client
          state: latest

      - name: yum kernel
        yum:
          name:
            - kernel-4.18.0-240.el8
            - kernel-devel-4.18.0-240.el8
            - kernel-tools-4.18.0-240.el8
            - kernel-tools-libs-4.18.0-240.el8
          state: latest

