---
  - name: install lustre server
    hosts:
      - client
    tasks:
      - name: create lustre.repo
        copy:
          src: /etc/yum.repos.d/lustre.repo
          dest: /etc/yum.repos.d/lustre.repo
      
      - name: yum install epel-release
        command: yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm -y
      
      - name: yum install dkms
        yum:
          name: dkms
          state: latest

      - name: yum install e2fsprogs
        yum:
          name: e2fsprogs
          state: latest

      - name: rpm -ivh kernel-devel
        yum:
          name: http://mirrors.portworx.com/mirrors/http/mirror.centos.org/centos/8/BaseOS/x86_64/os/Packages/kernel-devel-4.18.0-240.el8.x86_64.rpm
          state: latest
