---
  - name: install lustre server
    hosts:
      - oss
    tasks:
      - name: create lustre.repo
        copy:
          src: /etc/yum.repos.d/lustre.repo
          dest: /etc/yum.repos.d/lustre.repo
      
      - name: rpm -Uvh ZFS
        command: rpm -Uvh http://download.zfsonlinux.org/epel/zfs-release.el8_3.noarch.rpm

      - name: yum install zfs
        yum:
          name: zfs
          state: latest

